### ISSUE TITLE
Roles page does not work

### ISSUE THREAD

**Issue by skoro** [justintadlock/members#142]
```
2017/07/20 21:22:56 [error] 24735#0: *3195 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Members_Role_List_Table' not found in /home/sites/wp.ion.pp.ua/wp-content/plugins/members/admin/class-roles.php:181
Stack trace:
#0 /home/sites/wp.ion.pp.ua/wp-content/plugins/members/admin/class-manage-roles.php(148): Members_Admin_Roles->page()
#1 /home/sites/wp.ion.pp.ua/wp-includes/class-wp-hook.php(298): Members_Admin_Manage_Roles->page('')
#2 /home/sites/wp.ion.pp.ua/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#3 /home/sites/wp.ion.pp.ua/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /home/sites/wp.ion.pp.ua/wp-admin/admin.php(222): do_action('users_page_role...')
#5 /home/sites/wp.ion.pp.ua/wp-admin/users.php(11): require_once('/home/sites/wp....')
#6 {main}
```

PHP 7.1.7-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 10:07:42) ( NTS )
nginx 1.4.6

**Comment by justintadlock** [comment]
Looks like you're on an outdated version of the plugin or missing some files.  None of the three classes listed there are in the latest 2.0.0 version.

You can grab a clean copy of the latest here: https://wordpress.org/plugins/members/
